commands:
  restart:
    context: host
    execute:
      - echo "restarting $service_name"
      - docker restart $service_name
      - echo "$service_name restarted"
    parameters: [service_name]

  restart-middleware:
    context: host
    execute:
      - echo "Putting middleware down"
      - docker compose -f ${COMPOSE_FILE} --profile=${COMPOSE_PROFILE} --env-file=${COMPOSE_ENV_FILE} down middleware
      - echo "Building middleware with no cache"
      - docker compose -f ${COMPOSE_FILE} --profile=${COMPOSE_PROFILE} --env-file=${COMPOSE_ENV_FILE} build middleware --no-cache
      - echo "Deploying new middleware version"
      - docker compose -f ${COMPOSE_FILE} --profile=${COMPOSE_PROFILE} --env-file=${COMPOSE_ENV_FILE} up -d

  service-deploy:
    context: host
    execute:
      - { type: file, filename: 'service_deployer.sh' }

  pull_latest:
    context: host
    execute: git pull
